#!/usr/bin/env python3

import sys
sys.path.append(".")

import progressBar
import color

with open("/sys/class/power_supply/BAT0/status") as status:
    current = status.readline().split()
    if current[0] != "Discharging":
        bat = " "
    else:
        bat = " "

with open("/sys/class/power_supply/BAT0/capacity") as BAT0:
    perc = int(BAT0.readline())
    bat += progressBar.bat(perc) + " %d%%" %perc

print(bat)
print(bat)
print(color.genColor(perc))
print("#000000")
