#!/bin/env python3

import sys
sys.path.append(".")

from progressBar import genProgressBar
from color import genColor

with open("/sys/class/power_supply/BAT0/status") as status:
    current = status.readline().split()
    if current[0] != "Discharging":
        bat = "ﮣ "
    else:
        bat = " "

with open("/sys/class/power_supply/BAT0/capacity") as BAT0:
    perc = int(BAT0.readline())
    bat += genProgressBar(perc) + " %d%%" %perc

print(bat)
print(bat)
print(genColor(perc))
print("#000000")
