#!/usr/bin/env python3

import sys
import subprocess
sys.path.append(".")

from color import genColor
from progressBar import wifiProgressBar

with open("/sys/class/net/wlp3s0/operstate", "r") as stat:
    if stat.readline() == "down":
        print("ﲁ")
        print("ﲁ")
        print(genColor(0))
        print("#000000")
        sys.exit(0)

dbm = subprocess.run(["iw", "dev", "wlp3s0", "link"], capture_output=True, text=True)
temp = dbm.stdout.find("dBm")
perc = (int(dbm.stdout[temp - 4: temp]) + 100) * 2
if perc > 100 : perc = 100

bar = wifiProgressBar(perc)

print(bar, "%d%%" % perc)
print(bar, "%d%%" % perc)
print(genColor(perc))
print("#000000")
